FROM local:dydxprotocol

# Install bash and curl
RUN apk add --no-cache bash curl

# Copy the setup script
COPY setup.sh /setup.sh
RUN chmod +x /setup.sh

# Set the script as the entry point
ENTRYPOINT ["/setup.sh"] 